tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.0.5/types.yaml
  - plugin:cloudify-kubernetes-plugin

inputs:
  client_config:
    type: cloudify.kubernetes.types.ClientConfig
  definition:
    type: cloudify.kubernetes.types.ResourceDefinition
  options:
    type: dict
  validate_status:
    type: boolean
    default: false
  allow_node_redefinition:
    type: boolean
    default: false

node_templates:
  resource:
    type: cloudify.kubernetes.resources.Deployment
    properties:
      client_config: { get_input: client_config }
      definition: { get_input: definition }
      options: { get_input: options }
      validate_resource_status: { get_input: validate_status }
      allow_node_redefinition: { get_input: allow_node_redefinition }

outputs:
  kubernetes:
    description: Kubernetes environment description
    value: { get_attribute: [ resource, kubernetes ] }
